ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'LAWN_MAINTENANCE';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'LANDSCAPE_MAINTENANCE';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'LANDSCAPE_INSTALLATION';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'PROPERTY_CLEANUP_REFRESH';
ALTER TYPE "ServiceType" ADD VALUE IF NOT EXISTS 'NOT_SURE';
